Ci pipeline
eclipse-ee4j/glassfish pull request #22584
Opened 2018-09-27 21:24 UTC by romain-grecourt

First cut of a declarative pipeline for GlassFish.

2018-09-28 07:16 UTC, vinayvishal commented on nucleus/parent/pom.xml
> +        <repository>
Do we need to have this maven.java.net repository configuration?

2018-10-01 08:26 UTC, m0mus approved these changes
LGTM

2018-10-01 08:28 UTC, m0mus commented
@romain-grecourt Please sign your commit. It's a requirement for iP validation check.

2018-10-01 08:29 UTC, m0mus requested changes
Please sign your commit. It's a requirement for iP validation check.

2018-10-03 08:04 UTC, vinayvishal commented
> Need to remake the PR to sign this off.
> Is the sign-off kept with squashing ?

One possibility could be, amend the last commit with sign off option and then force push your changes to the corresponding branch.

2018-10-11 01:29 UTC, romain-grecourt commented
Thanks, sounds like a good option.
I'll force push to avoid re-creating a new PR.

2018-11-20 02:40 UTC, closed without merging