remove pfl-asm dependency
eclipse-ee4j/glassfish pull request #22890
Opened 2020-02-11 18:08 UTC by russgold

Signed-off-by: Russell Gold <russell.gold@oracle.com>

Remove dependency on internal pfl module

2020-02-12 09:37 UTC, Cousjava approved these changes

2020-02-12 10:11 UTC, Cousjava requested changes
I tried building this and glassfish failed to start due to an OSGi dependency on pfl-asm. As other pfl modules depend on pfl-asm, this is required.

2020-04-07 16:08 UTC, russgold commented
Thanks; I am going to need to fix pfl first.

2020-04-07 16:08 UTC, closed without merging

2020-04-09 14:25 UTC, Cousjava commented
@russgold I already have a PR into pfl at eclipse-ee4j/orb-gmbal-pfl#30