Fix the web_jsp devtests
eclipse-ee4j/glassfish pull request #23410
Opened 2021-03-07 11:33 UTC by arjantijms

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

2021-03-07 12:17 UTC, hussainnm requested changes
Is there a need to check-in the below class file?
- appserver/tests/appserv-tests/devtests/web/jspReloadGeneratedServletIfUpdated/test_jsp.class

Do we need to check-in the jar files if they can be generated at build time?

- appserver/tests/appserv-tests/devtests/web/jspConfigUsePrecompiled2/lib/jsps.jar
- appserver/tests/appserv-tests/devtests/web/jspCustomTaglibBundledAsJar/lib/mytaglib.jar
- appserver/tests/appserv-tests/devtests/web/jspInWebappWithBundledXercesImpl/lib/mytaglib.jar

2021-03-07 14:03 UTC, arjantijms commented
> Do we need to check-in the jar files if they can be generated at build time?

Technically I'd rather not, but that's the way the tests have already been setup, so this is the least effort way to make them run again. If you'd want to update the PR to generate the jar at build time, then +1 from me.

2021-03-07 14:43 UTC, hussainnm approved these changes

2021-03-08 13:01 UTC, smillidge approved these changes

2021-03-08 13:01 UTC, merged