Tidying / formatting of poms in nucleus module
eclipse-ee4j/glassfish pull request #23411
Opened 2021-03-08 14:50 UTC by arjantijms

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

2021-03-08 16:50 UTC, dmatej requested changes
If you would fix those comments I pointed at, I would approve it ;-)

2021-03-08 16:50 UTC, dmatej commented on nucleus/core/bootstrap/pom.xml
> -            <!--
I would start the comment on the new line ...

2021-03-08 16:50 UTC, dmatej commented on nucleus/core/bootstrap/pom.xml
> +            <plugin><!-- We package simple-glassfish-api classes in this bundle for embedded scenario, we expect user to
Here again, NL. Also groupId is not required if it has this value.

2021-03-08 16:50 UTC, dmatej commented on nucleus/admin/util/pom.xml
> +        <dependency><!-- We compile against the security module but we don't want to create a hard dependency because that
New line

2021-03-08 16:50 UTC, dmatej commented on nucleus/featuresets/atomic/pom.xml
> +        <!-- We install fileinstall bundle which monitors modules dir and autodeploy dir for addition/removal/updation of
Weird formatting here ...

2021-03-08 16:50 UTC, dmatej commented on nucleus/featuresets/atomic/pom.xml
> +        <!-- <dependency> <groupId>org.glassfish.jersey.media</groupId> <artifactId>jersey-media-json-processing</artifactId>
Fix formatting or delete it.

2021-03-08 16:50 UTC, dmatej commented on nucleus/featuresets/nucleus/pom.xml
> +        <!-- <dependency> <groupId>jakarta.xml.bind</groupId> <artifactId>jakarta.xml.bind-api</artifactId> <exclusions>
Fix formatting or delete it.

2021-03-09 16:26 UTC, dmatej approved these changes

2021-03-09 16:40 UTC, jGauravGupta approved these changes

2021-03-09 17:24 UTC, merged