Fix #24593 Error message is not displayed when Undeploy fails in Admin Console.
eclipse-ee4j/glassfish pull request #24594
Opened 2023-09-19 09:40 UTC by kaido207

* Fixes #24593

This method was replaced on https://github.com/eclipse-ee4j/glassfish/commit/d64fe7d005c8fff2311fbb7c1053d26f70c54531 .  
At that time, `gf.navigate` had a bug, but it is fixed now on https://github.com/eclipse-ee4j/glassfish-jsftemplating/pull/93 .

2023-09-19 09:49 UTC, arjantijms requested changes
lgtm, although we typically put the latest copyright line at the top, not at the bottom

2023-09-19 09:59 UTC, kaido207 commented
Sure, I modified it.

2023-09-19 13:04 UTC, OndroMih approved these changes

2023-09-19 14:20 UTC, arjantijms approved these changes

2023-09-19 14:20 UTC, merged

2023-09-22 06:57 UTC, kaido207 commented
> I wonder if gf.redirect works in other places or it should be replaced with gf.navigate also elsewhere: https://github.com/search?q=repo%3Aeclipse-ee4j%2Fglassfish%20%22gf.redirect%22&type=code
> 
> Could you check some of those places too if you can? It doesn't need to be fixed in this PR though.

Sure, I'm trying it.