Update the Administration Console description in the Administration Guide
eclipse-ee4j/glassfish pull request #24917
Opened 2024-04-16 19:46 UTC by avpinchuk

* Delete irrelevant Window info.
* Add the Administration Console startup options.

2024-04-16 19:47 UTC, avpinchuk commented
@OndroMih, please review.

2024-04-16 20:10 UTC, dmatej approved these changes

2024-04-16 22:39 UTC, OndroMih requested changes

2024-04-16 22:39 UTC, OndroMih commented on docs/administration-guide/src/main/asciidoc/overview.adoc
> +The Administration Console loads on demand the first access it. This is a default option.
```suggestion
The Administration Console loads on demand when its first accessed. This is the default option.
```

2024-04-16 22:39 UTC, OndroMih commented on docs/administration-guide/src/main/asciidoc/overview.adoc
> +`server.admin-service.property.adminConsoleStartup` to a value `default`.
```suggestion
`server.admin-service.property.adminConsoleStartup` to the value `default`.
```

2024-04-16 22:39 UTC, OndroMih commented on docs/administration-guide/src/main/asciidoc/overview.adoc
> +You can display the help material for a page in the Administration
```suggestion
##### Help pages in the Administration Console

You can display the help material for a page in the Administration
```

2024-04-17 13:42 UTC, arjantijms approved these changes

2024-04-17 13:42 UTC, merged